INSERT INTO roles (name, description)
VALUES ('oauth_incomplete', 'User role created by Oauth login automatically, but username is not defined.'),
       ('member', 'Default user role after completing registration.'),
       ('moderator', 'The one who moderates contents.'),
       ('admin', 'The Supreme Leader.'),
       ('banned', 'Bad behavior user.');

INSERT INTO role_permissions (module, action, role_id)
VALUES
       ('comment', 'read', (SELECT id FROM roles WHERE name = 'admin')),
       ('comment', 'post', (SELECT id FROM roles WHERE name = 'admin')),
       ('comment', 'modify', (SELECT id FROM roles WHERE name = 'admin')),
       ('comment', 'delete', (SELECT id FROM roles WHERE name = 'admin')),
       ('book', 'read', (SELECT id FROM roles WHERE name = 'admin')),
       ('book', 'post', (SELECT id FROM roles WHERE name = 'admin')),
       ('book', 'modify', (SELECT id FROM roles WHERE name = 'admin')),
       ('book', 'delete', (SELECT id FROM roles WHERE name = 'admin')),
       ('chapter', 'read', (SELECT id FROM roles WHERE name = 'admin')),
       ('chapter', 'post', (SELECT id FROM roles WHERE name = 'admin')),
       ('chapter', 'modify', (SELECT id FROM roles WHERE name = 'admin')),
       ('chapter', 'delete', (SELECT id FROM roles WHERE name = 'admin')),
       ('author', 'read', (SELECT id FROM roles WHERE name = 'admin')),
       ('author', 'post', (SELECT id FROM roles WHERE name = 'admin')),
       ('author', 'modify', (SELECT id FROM roles WHERE name = 'admin')),
       ('author', 'delete', (SELECT id FROM roles WHERE name = 'admin')),
       ('like', 'read', (SELECT id FROM roles WHERE name = 'admin')),
       ('like', 'post', (SELECT id FROM roles WHERE name = 'admin')),
       ('role', 'modify', (SELECT id FROM roles WHERE name = 'admin')),

       ('comment', 'read', (SELECT id FROM roles WHERE name = 'member')),
       ('comment', 'post', (SELECT id FROM roles WHERE name = 'member')),
       ('comment', 'modifySelf', (SELECT id FROM roles WHERE name = 'member')),
       ('comment', 'deleteSelf', (SELECT id FROM roles WHERE name = 'member')),
       ('book', 'read', (SELECT id FROM roles WHERE name = 'member')),
       ('book', 'post', (SELECT id FROM roles WHERE name = 'member')),
       ('book', 'modifySelf', (SELECT id FROM roles WHERE name = 'member')),
       ('chapter', 'read', (SELECT id FROM roles WHERE name = 'member')),
       ('chapter', 'post', (SELECT id FROM roles WHERE name = 'member')),
       ('chapter', 'modifySelf', (SELECT id FROM roles WHERE name = 'member')),
       ('chapter', 'deleteSelf', (SELECT id FROM roles WHERE name = 'member')),
       ('author', 'read', (SELECT id FROM roles WHERE name = 'member')),
       ('author', 'post', (SELECT id FROM roles WHERE name = 'member')),
       ('like', 'read', (SELECT id FROM roles WHERE name = 'member')),
       ('like', 'post', (SELECT id FROM roles WHERE name = 'member')),

       ('comment', 'read', (SELECT id FROM roles WHERE name = 'moderator')),
       ('comment', 'post', (SELECT id FROM roles WHERE name = 'moderator')),
       ('comment', 'modifySelf', (SELECT id FROM roles WHERE name = 'moderator')),
       ('comment', 'delete', (SELECT id FROM roles WHERE name = 'moderator')),
       ('book', 'read', (SELECT id FROM roles WHERE name = 'moderator')),
       ('book', 'post', (SELECT id FROM roles WHERE name = 'moderator')),
       ('book', 'modify', (SELECT id FROM roles WHERE name = 'moderator')),
       ('book', 'delete', (SELECT id FROM roles WHERE name = 'moderator')),
       ('chapter', 'read', (SELECT id FROM roles WHERE name = 'moderator')),
       ('chapter', 'post', (SELECT id FROM roles WHERE name = 'moderator')),
       ('chapter', 'modify', (SELECT id FROM roles WHERE name = 'moderator')),
       ('chapter', 'delete', (SELECT id FROM roles WHERE name = 'moderator')),
       ('author', 'read', (SELECT id FROM roles WHERE name = 'moderator')),
       ('author', 'post', (SELECT id FROM roles WHERE name = 'moderator')),
       ('author', 'modify', (SELECT id FROM roles WHERE name = 'moderator')),
       ('author', 'delete', (SELECT id FROM roles WHERE name = 'moderator')),
       ('like', 'read', (SELECT id FROM roles WHERE name = 'moderator')),
       ('like', 'post', (SELECT id FROM roles WHERE name = 'moderator'));