// Code generated by sqlc. DO NOT EDIT.
// source: book_group.sql

package db

import (
	"context"
	"database/sql"
)

const bookGroupById = `-- name: BookGroupById :one
SELECT id, title, description, date_created, owner_id, primary_cover_art_id
FROM book_groups
WHERE id = $1
`

func (q *Queries) BookGroupById(ctx context.Context, id int32) (BookGroup, error) {
	row := q.db.QueryRow(ctx, bookGroupById, id)
	var i BookGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DateCreated,
		&i.OwnerID,
		&i.PrimaryCoverArtID,
	)
	return i, err
}

const bookGroupsByTitle = `-- name: BookGroupsByTitle :many
SELECT id, title, description, date_created, owner_id, primary_cover_art_id
FROM book_groups
WHERE  LOWER(title) LIKE '%' || $1 || '%'
ORDER BY id
OFFSET $2 ROWS
    FETCH FIRST $3 ROWS ONLY
`

type BookGroupsByTitleParams struct {
	Column1 sql.NullString `json:"column1"`
	Offset  int32          `json:"offset"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) BookGroupsByTitle(ctx context.Context, arg BookGroupsByTitleParams) ([]BookGroup, error) {
	rows, err := q.db.Query(ctx, bookGroupsByTitle, arg.Column1, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookGroup
	for rows.Next() {
		var i BookGroup
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DateCreated,
			&i.OwnerID,
			&i.PrimaryCoverArtID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBookGroup = `-- name: DeleteBookGroup :exec
DELETE FROM book_groups
WHERE id = $1
`

func (q *Queries) DeleteBookGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBookGroup, id)
	return err
}

const insertBookGroup = `-- name: InsertBookGroup :one
INSERT INTO book_groups(title, description,owner_id)
VALUES ($1, $2,$3)
RETURNING id, title, description, date_created, owner_id, primary_cover_art_id
`

type InsertBookGroupParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	OwnerID     int32          `json:"ownerID"`
}

func (q *Queries) InsertBookGroup(ctx context.Context, arg InsertBookGroupParams) (BookGroup, error) {
	row := q.db.QueryRow(ctx, insertBookGroup, arg.Title, arg.Description, arg.OwnerID)
	var i BookGroup
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DateCreated,
		&i.OwnerID,
		&i.PrimaryCoverArtID,
	)
	return i, err
}

const updateBookGroup = `-- name: UpdateBookGroup :exec
UPDATE book_groups
SET title = $2,
    description=$3,
    owner_id=$4
WHERE id = $1
`

type UpdateBookGroupParams struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	OwnerID     int32          `json:"ownerID"`
}

func (q *Queries) UpdateBookGroup(ctx context.Context, arg UpdateBookGroupParams) error {
	_, err := q.db.Exec(ctx, updateBookGroup,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
	)
	return err
}
