// Code generated by sqlc. DO NOT EDIT.
// source: book_group_art.sql

package db

import (
	"context"
)

const deleteBookGroupArt = `-- name: DeleteBookGroupArt :exec
DELETE
FROM book_group_arts
WHERE book_group_id = $1
  AND image_id = $2
`

type DeleteBookGroupArtParams struct {
	BookGroupID int32 `json:"bookGroupID"`
	ImageID     int32 `json:"imageID"`
}

func (q *Queries) DeleteBookGroupArt(ctx context.Context, arg DeleteBookGroupArtParams) error {
	_, err := q.db.Exec(ctx, deleteBookGroupArt, arg.BookGroupID, arg.ImageID)
	return err
}

const insertBookGroupArt = `-- name: InsertBookGroupArt :one
INSERT INTO book_group_arts(book_group_id, image_id)
VALUES ($1, $2)
RETURNING book_group_id, image_id
`

type InsertBookGroupArtParams struct {
	BookGroupID int32 `json:"bookGroupID"`
	ImageID     int32 `json:"imageID"`
}

func (q *Queries) InsertBookGroupArt(ctx context.Context, arg InsertBookGroupArtParams) (BookGroupArt, error) {
	row := q.db.QueryRow(ctx, insertBookGroupArt, arg.BookGroupID, arg.ImageID)
	var i BookGroupArt
	err := row.Scan(&i.BookGroupID, &i.ImageID)
	return i, err
}
