// Code generated by sqlc. DO NOT EDIT.
// source: book_group_arts.sql

package db

import (
	"context"
)

const getBookGroupCoverArts = `-- name: GetBookGroupCoverArts :many
SELECT images.path
FROM images JOIN book_group_arts bga on images.id = bga.image_id
            JOIN book_groups bg on bga.book_group_id = bg.id
WHERE bg.id = $1
`

func (q *Queries) GetBookGroupCoverArts(ctx context.Context, id int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getBookGroupCoverArts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
