// Code generated by sqlc. DO NOT EDIT.
// source: views.sql

package db

import (
	"context"
	"time"
)

const getViewByMonth = `-- name: GetViewByMonth :one
SELECT SUM(count) as viewByMonth FROM book_chapter_views
WHERE book_chapter_id = $1
AND view_date >= now() - interval '1 month'
`

func (q *Queries) GetViewByMonth(ctx context.Context, bookChapterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getViewByMonth, bookChapterID)
	var viewbymonth int64
	err := row.Scan(&viewbymonth)
	return viewbymonth, err
}

const getViewByWeek = `-- name: GetViewByWeek :one
SELECT SUM(count) as viewByWeek FROM book_chapter_views
WHERE book_chapter_id = $1
  AND view_date >= now() - interval '1 week'
`

func (q *Queries) GetViewByWeek(ctx context.Context, bookChapterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getViewByWeek, bookChapterID)
	var viewbyweek int64
	err := row.Scan(&viewbyweek)
	return viewbyweek, err
}

const getViewByYear = `-- name: GetViewByYear :one
SELECT SUM(count) as viewByYear FROM book_chapter_views
WHERE book_chapter_id = $1
  AND view_date >= now() - interval '1 year'
`

func (q *Queries) GetViewByYear(ctx context.Context, bookChapterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getViewByYear, bookChapterID)
	var viewbyyear int64
	err := row.Scan(&viewbyyear)
	return viewbyyear, err
}

const upsertViewByDate = `-- name: UpsertViewByDate :exec
INSERT INTO book_chapter_views(book_chapter_id, view_date)
VALUES ($1, $2)
ON CONFLICT(book_chapter_id, view_date)
DO UPDATE SET count = count + 1
`

type UpsertViewByDateParams struct {
	BookChapterID int32     `json:"bookChapterID"`
	ViewDate      time.Time `json:"viewDate"`
}

func (q *Queries) UpsertViewByDate(ctx context.Context, arg UpsertViewByDateParams) error {
	_, err := q.db.Exec(ctx, upsertViewByDate, arg.BookChapterID, arg.ViewDate)
	return err
}
