// Code generated by sqlc. DO NOT EDIT.
// source: views.sql

package db

import (
	"context"
	"time"
)

const getBookGroupView = `-- name: GetBookGroupView :one
SELECT COALESCE(sum(count), 0) as totalView
FROM book_chapter_views JOIN book_chapters bc on book_chapter_views.book_chapter_id = bc.id
                        JOIN book_groups bg on bc.book_group_id = bg.id
WHERE bg.id = $1
`

func (q *Queries) GetBookGroupView(ctx context.Context, id int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getBookGroupView, id)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getViewByMonth = `-- name: GetViewByMonth :one
SELECT COALESCE(sum(count), 0) as viewByMonth FROM book_chapter_views
WHERE book_chapter_id = $1
AND view_date >= now() - interval '1 month'
`

func (q *Queries) GetViewByMonth(ctx context.Context, bookChapterID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getViewByMonth, bookChapterID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getViewByWeek = `-- name: GetViewByWeek :one
SELECT COALESCE(sum(count), 0) as viewByWeek FROM book_chapter_views
WHERE book_chapter_id = $1
  AND view_date >= now() - interval '1 week'
`

func (q *Queries) GetViewByWeek(ctx context.Context, bookChapterID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getViewByWeek, bookChapterID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getViewByYear = `-- name: GetViewByYear :one
SELECT COALESCE(sum(count), 0) as viewByYear FROM book_chapter_views
WHERE book_chapter_id = $1
  AND view_date >= now() - interval '1 year'
`

func (q *Queries) GetViewByYear(ctx context.Context, bookChapterID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getViewByYear, bookChapterID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const upsertViewByDate = `-- name: UpsertViewByDate :exec
INSERT INTO book_chapter_views(book_chapter_id, view_date)
VALUES ($1, $2)
ON CONFLICT(book_chapter_id, view_date)
DO UPDATE SET count = count + 1
`

type UpsertViewByDateParams struct {
	BookChapterID int32     `json:"bookChapterID"`
	ViewDate      time.Time `json:"viewDate"`
}

func (q *Queries) UpsertViewByDate(ctx context.Context, arg UpsertViewByDateParams) error {
	_, err := q.db.Exec(ctx, upsertViewByDate, arg.BookChapterID, arg.ViewDate)
	return err
}
